### PR TITLE
Create Sanwave

### PR DESCRIPTION
**Pull request by imsan**

### CODE REVIEW

**Comment by imsan** [comment]
Help to upload this source to web page

**Comment by softdev629** [comment]
who are you?
what are you going to do?

**Comment by imsan** [comment]
Hello Sir
Actully i do qr code & nfc business card marketing in my local.area .
I want to develop software like this one. So i just install to know more
about it.
Is there any problem sir ?
can you help me to start website with this code.
Can i upload this to my webserver please.
Thank you for your concern .
Best Regard
Sanjay Poudel

**Comment by softdev629** [comment]
No problems with it.
Feel free to use.
This is just old project since it uses PHP and CodeIgniter framework.
What is your purpose?

**Comment by imsan** [comment]
Great!
Thank you

**Pull request closed without merging**
